#!/usr/bin/env python3
"""Build src/c/catalog_data.h from the Yale Bright Star Catalog (bsc5-short.json)."""
from __future__ import print_function

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_JSON = os.path.join(ROOT, "tools", "bsc5-short.json")
OUT_H = os.path.join(ROOT, "src", "c", "catalog_data.h")
BSC_URL = (
    "https://raw.githubusercontent.com/brettonw/YaleBrightStarCatalog/"
    "master/bsc5-short.json"
)

MAG_LIMIT = 4.5
MAX_NAMES = 254
MAX_NAME_LEN = 18

RA_RE = re.compile(
    r"(\d+)\s*h\s*(\d+)\s*m\s*([0-9.]+)\s*s", re.IGNORECASE
)
DEC_RE = re.compile(
    r"([+\-]?)\s*(\d+)\s*[^\d]+(\d+)\s*[^\d]+(\d+)"
)


def parse_ra_hours(text):
    m = RA_RE.search(text or "")
    if not m:
        return None
    h = float(m.group(1))
    mi = float(m.group(2))
    s = float(m.group(3))
    return h + mi / 60.0 + s / 3600.0


def parse_dec_deg(text):
    m = DEC_RE.search(text or "")
    if not m:
        return None
    sign = -1.0 if m.group(1) == "-" else 1.0
    d = float(m.group(2))
    mi = float(m.group(3))
    s = float(m.group(4))
    return sign * (d + mi / 60.0 + s / 3600.0)


def load_bsc():
    if os.path.isfile(SRC_JSON):
        with open(SRC_JSON, "r", encoding="utf-8") as f:
            return json.load(f)
    try:
        from urllib.request import urlopen
    except ImportError:
        from urllib2 import urlopen
    print("Downloading", BSC_URL)
    data = urlopen(BSC_URL).read().decode("utf-8")
    os.makedirs(os.path.dirname(SRC_JSON), exist_ok=True)
    with open(SRC_JSON, "w", encoding="utf-8") as f:
        f.write(data)
    return json.loads(data)


def c_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    rows = load_bsc()
    stars = []
    for row in rows:
        try:
            mag = float(row.get("V"))
        except (TypeError, ValueError):
            continue
        if mag > MAG_LIMIT:
            continue
        ra_h = parse_ra_hours(row.get("RA"))
        dec = parse_dec_deg(row.get("Dec"))
        if ra_h is None or dec is None:
            continue
        name = (row.get("N") or "").strip()
        if name:
            name = " ".join(name.split())
            if len(name) > MAX_NAME_LEN:
                name = name[:MAX_NAME_LEN].rstrip()
        stars.append({
            "ra_h": ra_h,
            "dec": dec,
            "mag": mag,
            "name": name,
        })

    # Assign names to the brightest stars first so famous names are kept.
    names = [""]
    name_to_id = {}
    for star in sorted(stars, key=lambda s: s["mag"]):
        n = star["name"]
        if not n:
            star["name_id"] = 0
            continue
        if n not in name_to_id:
            if len(names) > MAX_NAMES:
                star["name_id"] = 0
                continue
            name_to_id[n] = len(names)
            names.append(n)
        star["name_id"] = name_to_id[n]

    # Dim first so bright stars draw on top.
    stars.sort(key=lambda s: -s["mag"])

    os.makedirs(os.path.dirname(OUT_H), exist_ok=True)
    with open(OUT_H, "w", encoding="utf-8") as f:
        f.write("/* Generated by tools/gen_catalog.py — do not edit. */\n")
        f.write("#pragma once\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("#define CATALOG_STAR_COUNT %d\n" % len(stars))
        f.write("#define CATALOG_NAME_COUNT %d\n\n" % (len(names) - 1))
        f.write("static const PackedStar CATALOG_STARS[CATALOG_STAR_COUNT] = {\n")
        for star in stars:
            ra_u16 = int(round((star["ra_h"] / 24.0) * 65536.0)) & 0xFFFF
            if ra_u16 == 65536:
                ra_u16 = 0
            dec_cdeg = int(round(star["dec"] * 100.0))
            if dec_cdeg > 32767:
                dec_cdeg = 32767
            if dec_cdeg < -32768:
                dec_cdeg = -32768
            mag10 = int(round(star["mag"] * 10.0))
            if mag10 > 127:
                mag10 = 127
            if mag10 < -128:
                mag10 = -128
            f.write(
                "  {%5d, %6d, %4d, %3d},\n"
                % (ra_u16, dec_cdeg, mag10, star["name_id"])
            )
        f.write("};\n\n")
        f.write("static const char *const CATALOG_NAMES[CATALOG_NAME_COUNT + 1] = {\n")
        for n in names:
            f.write('  "%s",\n' % c_escape(n))
        f.write("};\n")

    named = sum(1 for s in stars if s["name_id"])
    print("Wrote %s" % OUT_H)
    print("  stars: %d (mag <= %.1f)" % (len(stars), MAG_LIMIT))
    print("  named: %d" % named)


if __name__ == "__main__":
    sys.exit(main() or 0)
